import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { HeroThemeProvider } from "@/contexts/hero-theme-context";
import Link from "next/link";
import { ThemeToggle } from "@/components/theme-toggle";
import { HeaderWrapper } from "@/components/header-wrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem={false}
          disableTransitionOnChange
        >
          <HeroThemeProvider>
            <HeaderWrapper />
            
            {/* Main content wrapper */}
            <main className="pt-20 min-h-screen w-full">
              {children}
            </main>
          </HeroThemeProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
